name: ugc_service

# PROFILES:
#   run: runs all services
#   

include:
  - './infra/mongo/compose.yml'
  - './infra/kafka/compose.yml'
  - './infra/ELK/compose.yml'
  - './api/tests/compose.yml'


services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    image: ${API_DOCKER_IMAGE:?Api docker image name is required}
    restart: unless-stopped
    command: ["uvicorn", "--reload", "--host", "0.0.0.0", "--port", "${APP_PORT:-8000}", "--workers", "3", "--factory", "src.main:init"]
    volumes:
      - ./api/:/app/
    secrets:
      - mongo-root-user
      - mongo-root-pwd
    env_file:
      - ./.env
    healthcheck:
      start_interval: 10s
      start_period: 10s
      test: curl -sS localhost:8000/_ping > /dev/null && exit 0 || exit 1
      interval: 10s
      retries: 5
    profiles:
      - api
      - run
    depends_on:
      kafka0:
        condition: service_healthy
  consumer:
    container_name: analytics_events_consumer
    image: ${CONSUMER_DOCKER_IMAGE:?Consumer docker image name is required}
    build:
      context: ./ETL
      dockerfile: Dockerfile.etl
    volumes:
      - ./ETL/:/app/
    env_file:
      - ./ETL/.env
    depends_on:
      kafka0:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
    profiles:
      - kafka_cluster
      - run

  nginx:
    image: nginx:1.27.0-alpine
    configs:
      - source: nginx_conf
        target: /etc/nginx/nginx.conf
        mode: 0440
    volumes:
      - nginx_logs:/var/logs/nginx/
    depends_on:
      api:
        condition: service_healthy
    ports:
      - 80:80
    restart: unless-stopped
    profiles:
      - api
      - run

  clickhouse:
    container_name: clickhouse-server
    image: clickhouse:25.5.1
    env_file:
      - ./infra/clickhouse/.env  # CLICKHOUSE_USER & CLICKHOUSE_PASSWORD
    ports:
      - 18123:8123
      - 19000:9000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./infra/clickhouse/initdb:/docker-entrypoint-initdb.d/
    healthcheck:
      test: ["CMD", "clickhouse-client", "--host=localhost", "--query=SELECT 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    profiles:
      - kafka_cluster
      - run

configs:
  nginx_conf:
    file: ./infra/nginx/config/nginx.conf

volumes:
  nginx_logs:
    name: ugc_nginx_logs

secrets:
  mongo-root-user:
    name: ugc-mongo-root-username
    file: ./infra/mongo/secrets/root-user.txt
  mongo-root-pwd:
    name: ugc-mongo-root-pwd
    file: ./infra/mongo/secrets/root-pwd.txt
