[project]
name = "ugcservice"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.6",
    "motor==3.4.0",
    "pymongo[srv]==4.8.0",
    "uvicorn>=0.34.0",
]
