from typing import Any, Protocol, Self


class ReviewOperations(Protocol):
    async def add_review(self, user_id: Any, movie_id: Any, review: Any) -> None: ...
    async def update_review(self, user_id: Any, movie_id: Any, review: Any) -> None: ...
    async def delete_review(self, user_id: Any, movie_id: Any) -> None: ...


class ReviewList(Protocol):
    async def reviews(self, id: Any) -> Any: ...


class UOW(Protocol):
    async def __aenter__(self) -> Self: ...
    async def __aexit__(self, exc_type, exc, tb): ...
    async def commit(self): ...
    async def rollback(self): ...
