from typing import Any, Awaitable, Protocol


class ReviewOperations(Protocol):
    async def add_review(self, user_id: Any, movie_id: Any, review: Any) -> Awaitable[None]: ...
    async def update_review(self, user_id: Any, movie_id: Any, review: Any) -> Awaitable[None]: ...
    async def delete_review(self, user_id: Any, review_id: Any) -> Awaitable[None]: ...


class ReviewList(Protocol):
    async def reviews(self, movie_id: Any) -> Awaitable[Any]: ...