from typing import Any, Protocol

from src.core.protocols import ReviewList, ReviewOperations


class UserRepository(ReviewOperations, ReviewList, Protocol):
    async def get_data(self, user_id: Any) -> Any: ...
    async def add_bookmark(self, user_id: Any, movie_id: Any) -> bool: ...
    async def remove_bookmark(self, user_id: Any, movie_id: Any) -> None: ...
    async def bookmarks(self, user_id: Any) -> Any: ...
    async def rate_movie(self, user_id: Any, movie_id: Any) -> Any: ...


class MovieRepository(ReviewOperations, ReviewList, Protocol):
    async def rating(self, movie_id: Any) -> float: ...
    async def rate(self, user_id: Any, movie_id: Any) -> Any: ...
