FROM python:3.12.8-bullseye AS python


ENV PYTHONUNBUFFERED=1
ENV PYTHONDONTWRITEBYTECODE=1
ENV PIP_DISABLE_PIP_VERSION_CHECK=1

ARG BUILD=dev

WORKDIR /app

COPY ./requirements/consumer.${BUILD}.txt /app/requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY ./consumer.py /app/consumer.py
COPY ./config.py /app/config.py

CMD [ "python", "consumer.py" ]